Server:
  Port: 8080

spring:
  data:
    mongodb:
      username: mongo
      password: mongo123
      database: pulseops_masterdata
      authentication-database: admin
      host: localhost
      port: 27017

management.endpoints.web.exposure.include: '*'
app:
  cacheRefreshTime: 3600000

logging.level.org.springframework.data.mongodb.core.MongoTemplate: DEBUG